// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxnvxljwcukaguznuqwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bnZ4bGp3Y3VrYWd1em51cXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDM1NzcsImV4cCI6MjA3Mjc3OTU3N30.qJFP7eUHtfYcX3qRDDME1BMPtPdwYGkcaAF9l85OQ3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});